/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.*;
import controller.*;
import Model.*;
import javax.swing.*;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Matthew
 */
public class Frontend extends javax.swing.JFrame {

    User currentUser;
    
    /**
     * Creates new form Frontend
     */
    public Frontend() {
        initComponents();
    }
    
    private void doLogin(String userid, String password)
    {
        DataModel data = DataModel.getInstance();
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        
        this.currentUser = data.processLogin(userid, password);
        if(this.currentUser == null)
        {//If login fails blank panel and abort
            card.show(mainPanel, "Blank");
            return;
        }
                
        if (this.currentUser instanceof Administrator)
            card.show(mainPanel, "AdminView");
        else if (this.currentUser instanceof Doctor)
            card.show(mainPanel, "DoctorView");
        else if (this.currentUser instanceof Patient)
            card.show(mainPanel, "PatientView");
        else if (this.currentUser instanceof Secretary)
            card.show(mainPanel, "SecretaryView");
        
        btnLogin.setEnabled(false);
        btnLogout.setEnabled(true);
        btnAdminCreateMenu.setEnabled(false);
        txtUserId.setText("");
        txtPassword.setText("");
        displayUser(this.currentUser);
    }
    
    private void doLogout()
    {
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "Blank");
        this.currentUser = null;
        btnLogout.setEnabled(false);
        btnLogin.setEnabled(true);
        btnAdminCreateMenu.setEnabled(true);
        clearUserDisplay();
    }
    
    private void displayUser(User user)
    {
        txtInfoUserId.setText(user.getId());
        txtInfoFirstName.setText(user.getFirstName());
        txtInfoSurname.setText(user.getSurname());
        txtaInfoAddress.setText(user.getAddress());
    }
    
    private void clearUserDisplay()
    {
        txtInfoUserId.setText("");
        txtInfoFirstName.setText("");
        txtInfoSurname.setText("");
        txtaInfoAddress.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpAdminCreating = new javax.swing.ButtonGroup();
        btnAdminCreateMenu = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        AdminView = new javax.swing.JPanel();
        newAdminInputs1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaAdminAddress1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtAdminPassword1 = new javax.swing.JPasswordField();
        txtAdminSurname1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtAdminFirstName1 = new javax.swing.JTextField();
        btnCreateAdminAccount1 = new javax.swing.JButton();
        rdoSecretary = new javax.swing.JRadioButton();
        rdoDoctor = new javax.swing.JRadioButton();
        DoctorView = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SecretaryView = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PatientView = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Blank = new javax.swing.JPanel();
        AdminCreate = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtAdminAccountIdOutput = new javax.swing.JTextField();
        newAdminInputs = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaAdminAddress = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAdminPassword = new javax.swing.JPasswordField();
        txtAdminSurname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAdminFirstName = new javax.swing.JTextField();
        btnCreateAdminAccount = new javax.swing.JButton();
        UserInfo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtInfoFirstName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtInfoSurname = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaInfoAddress = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        txtInfoUserId = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        LoginInputs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JFormattedTextField();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Management System");

        btnAdminCreateMenu.setText("Create Admin");
        btnAdminCreateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCreateMenuActionPerformed(evt);
            }
        });

        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setLayout(new java.awt.CardLayout());

        newAdminInputs1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtaAdminAddress1.setColumns(20);
        txtaAdminAddress1.setRows(5);
        jScrollPane2.setViewportView(txtaAdminAddress1);

        jLabel12.setText("Address:");

        jLabel13.setText("Password:");

        jLabel14.setText("Surname:");

        jLabel15.setText("First Name:");

        btnCreateAdminAccount1.setText("Create New Account");
        btnCreateAdminAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAdminAccount1ActionPerformed(evt);
            }
        });

        btngrpAdminCreating.add(rdoSecretary);
        rdoSecretary.setText("Secretary");

        btngrpAdminCreating.add(rdoDoctor);
        rdoDoctor.setText("Doctor");

        javax.swing.GroupLayout newAdminInputs1Layout = new javax.swing.GroupLayout(newAdminInputs1);
        newAdminInputs1.setLayout(newAdminInputs1Layout);
        newAdminInputs1Layout.setHorizontalGroup(
            newAdminInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAdminInputs1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newAdminInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAdminInputs1Layout.createSequentialGroup()
                        .addGroup(newAdminInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newAdminInputs1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAdminInputs1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(newAdminInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(newAdminInputs1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(11, 11, 11)))
                .addGroup(newAdminInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtAdminFirstName1)
                    .addComponent(txtAdminSurname1)
                    .addComponent(jScrollPane2)
                    .addComponent(txtAdminPassword1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAdminInputs1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newAdminInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(newAdminInputs1Layout.createSequentialGroup()
                        .addComponent(rdoDoctor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoSecretary))
                    .addComponent(btnCreateAdminAccount1))
                .addContainerGap())
        );
        newAdminInputs1Layout.setVerticalGroup(
            newAdminInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAdminInputs1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newAdminInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtAdminFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newAdminInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtAdminSurname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newAdminInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtAdminPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(newAdminInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newAdminInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoSecretary)
                    .addComponent(rdoDoctor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateAdminAccount1)
                .addContainerGap())
        );

        javax.swing.GroupLayout AdminViewLayout = new javax.swing.GroupLayout(AdminView);
        AdminView.setLayout(AdminViewLayout);
        AdminViewLayout.setHorizontalGroup(
            AdminViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newAdminInputs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
        );
        AdminViewLayout.setVerticalGroup(
            AdminViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newAdminInputs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        mainPanel.add(AdminView, "AdminView");

        jLabel4.setText("Doctor Mode");

        javax.swing.GroupLayout DoctorViewLayout = new javax.swing.GroupLayout(DoctorView);
        DoctorView.setLayout(DoctorViewLayout);
        DoctorViewLayout.setHorizontalGroup(
            DoctorViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
            .addGroup(DoctorViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DoctorViewLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        DoctorViewLayout.setVerticalGroup(
            DoctorViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
            .addGroup(DoctorViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DoctorViewLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainPanel.add(DoctorView, "DoctorView");

        jLabel5.setText("Secretary Mode");

        javax.swing.GroupLayout SecretaryViewLayout = new javax.swing.GroupLayout(SecretaryView);
        SecretaryView.setLayout(SecretaryViewLayout);
        SecretaryViewLayout.setHorizontalGroup(
            SecretaryViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
            .addGroup(SecretaryViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SecretaryViewLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        SecretaryViewLayout.setVerticalGroup(
            SecretaryViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
            .addGroup(SecretaryViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SecretaryViewLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainPanel.add(SecretaryView, "SecretaryView");

        jLabel6.setText("PatientMode");

        javax.swing.GroupLayout PatientViewLayout = new javax.swing.GroupLayout(PatientView);
        PatientView.setLayout(PatientViewLayout);
        PatientViewLayout.setHorizontalGroup(
            PatientViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
            .addGroup(PatientViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PatientViewLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PatientViewLayout.setVerticalGroup(
            PatientViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
            .addGroup(PatientViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PatientViewLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainPanel.add(PatientView, "PatientView");

        javax.swing.GroupLayout BlankLayout = new javax.swing.GroupLayout(Blank);
        Blank.setLayout(BlankLayout);
        BlankLayout.setHorizontalGroup(
            BlankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );
        BlankLayout.setVerticalGroup(
            BlankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        mainPanel.add(Blank, "Blank");

        jLabel9.setText("Account Id:");

        txtAdminAccountIdOutput.setEditable(false);

        newAdminInputs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtaAdminAddress.setColumns(20);
        txtaAdminAddress.setRows(5);
        jScrollPane1.setViewportView(txtaAdminAddress);

        jLabel8.setText("Address:");

        jLabel11.setText("Password:");

        jLabel10.setText("Surname:");

        jLabel7.setText("First Name:");

        btnCreateAdminAccount.setText("Create Admin Account");
        btnCreateAdminAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAdminAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newAdminInputsLayout = new javax.swing.GroupLayout(newAdminInputs);
        newAdminInputs.setLayout(newAdminInputsLayout);
        newAdminInputsLayout.setHorizontalGroup(
            newAdminInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAdminInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newAdminInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAdminInputsLayout.createSequentialGroup()
                        .addGroup(newAdminInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newAdminInputsLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAdminInputsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(newAdminInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(newAdminInputsLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(11, 11, 11)))
                .addGroup(newAdminInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtAdminFirstName)
                    .addComponent(txtAdminSurname)
                    .addComponent(jScrollPane1)
                    .addComponent(txtAdminPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAdminInputsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateAdminAccount)
                .addContainerGap())
        );
        newAdminInputsLayout.setVerticalGroup(
            newAdminInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAdminInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newAdminInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAdminFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newAdminInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtAdminSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newAdminInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(newAdminInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateAdminAccount)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AdminCreateLayout = new javax.swing.GroupLayout(AdminCreate);
        AdminCreate.setLayout(AdminCreateLayout);
        AdminCreateLayout.setHorizontalGroup(
            AdminCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newAdminInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdminAccountIdOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        AdminCreateLayout.setVerticalGroup(
            AdminCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtAdminAccountIdOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(newAdminInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        mainPanel.add(AdminCreate, "AdminCreate");

        UserInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Your Information:");

        txtInfoFirstName.setEditable(false);

        jLabel16.setText("First Name:");

        jLabel17.setText("Surname:");

        txtInfoSurname.setEditable(false);

        txtaInfoAddress.setEditable(false);
        txtaInfoAddress.setColumns(20);
        txtaInfoAddress.setRows(5);
        jScrollPane3.setViewportView(txtaInfoAddress);

        jLabel18.setText("Address:");

        txtInfoUserId.setEditable(false);

        jLabel19.setText("User ID:");

        javax.swing.GroupLayout UserInfoLayout = new javax.swing.GroupLayout(UserInfo);
        UserInfo.setLayout(UserInfoLayout);
        UserInfoLayout.setHorizontalGroup(
            UserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserInfoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserInfoLayout.createSequentialGroup()
                        .addGroup(UserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(UserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtInfoUserId)
                            .addComponent(txtInfoFirstName)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtInfoSurname, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );
        UserInfoLayout.setVerticalGroup(
            UserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInfoUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(11, 11, 11)
                .addGroup(UserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInfoFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtInfoSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LoginInputs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("User ID:");

        jLabel2.setText("Password:");

        try {
            txtUserId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.setEnabled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginInputsLayout = new javax.swing.GroupLayout(LoginInputs);
        LoginInputs.setLayout(LoginInputsLayout);
        LoginInputsLayout.setHorizontalGroup(
            LoginInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(LoginInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPassword)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginInputsLayout.setVerticalGroup(
            LoginInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(LoginInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPassword)
                        .addComponent(btnLogout)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LoginInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdminCreateMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminCreateMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        this.doLogin(txtUserId.getText(), txtPassword.getText());
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnAdminCreateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCreateMenuActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "AdminCreate");
    }//GEN-LAST:event_btnAdminCreateMenuActionPerformed

    private void btnCreateAdminAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAdminAccountActionPerformed
        DataModel data = DataModel.getInstance();
        
        AdminBuilder builder = new AdminBuilder();
        
        builder.setUserNum(data.getHighestUserNum('A')+1);
        
        builder.setFirstName(txtAdminFirstName.getText());
        builder.setSurname(txtAdminSurname.getText());
        builder.setAddress(txtaAdminAddress.getText());
        builder.setPassword(new String(txtAdminPassword.getPassword()));
        
        Administrator admin = builder.build();
        
        if(data.addUser(admin))
        {
            txtAdminAccountIdOutput.setText(admin.getId());
            for (Component C: newAdminInputs.getComponents())
            {
                if (C instanceof JTextField || C instanceof JTextArea || C instanceof JPasswordField){
                    ((JTextComponent) C).setText("");
                }
            }
            txtaAdminAddress.setText("");//for some reason the above code misses the text area.
        }
    }//GEN-LAST:event_btnCreateAdminAccountActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.doLogout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCreateAdminAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAdminAccount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateAdminAccount1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frontend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminCreate;
    private javax.swing.JPanel AdminView;
    private javax.swing.JPanel Blank;
    private javax.swing.JPanel DoctorView;
    private javax.swing.JPanel LoginInputs;
    private javax.swing.JPanel PatientView;
    private javax.swing.JPanel SecretaryView;
    private javax.swing.JPanel UserInfo;
    private javax.swing.JButton btnAdminCreateMenu;
    private javax.swing.JButton btnCreateAdminAccount;
    private javax.swing.JButton btnCreateAdminAccount1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.ButtonGroup btngrpAdminCreating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel newAdminInputs;
    private javax.swing.JPanel newAdminInputs1;
    private javax.swing.JRadioButton rdoDoctor;
    private javax.swing.JRadioButton rdoSecretary;
    private javax.swing.JTextField txtAdminAccountIdOutput;
    private javax.swing.JTextField txtAdminFirstName;
    private javax.swing.JTextField txtAdminFirstName1;
    private javax.swing.JPasswordField txtAdminPassword;
    private javax.swing.JPasswordField txtAdminPassword1;
    private javax.swing.JTextField txtAdminSurname;
    private javax.swing.JTextField txtAdminSurname1;
    private javax.swing.JTextField txtInfoFirstName;
    private javax.swing.JTextField txtInfoSurname;
    private javax.swing.JTextField txtInfoUserId;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JFormattedTextField txtUserId;
    private javax.swing.JTextArea txtaAdminAddress;
    private javax.swing.JTextArea txtaAdminAddress1;
    private javax.swing.JTextArea txtaInfoAddress;
    // End of variables declaration//GEN-END:variables
}
